### ISSUE TITLE
I 💗 your screenshot!  

### ISSUE THREAD

**Issue by PySimpleGUI** [adyrosebrigg/pyWordle#1]
Thank you for posting a screenshot in your readme!  ![image](https://user-images.githubusercontent.com/46163555/161391517-4ddd316c-0639-46eb-a20f-dd6c02b6e85f.png)

You did a better job than I did on the interface.  I too don't play Wordle so I'm pretty clueless about it.  You'll find a simple version I did here:
https://pysimplegui.trinket.io/demo-programs#/games/wordle

It doesn't include the fancy "used letter" portion of the interface like yours does.  Very nice touch in your UI!

---------------

To answer your license question....

You're free to redistribute PySimpleGUI with your code if needed.  Generally, it's not needed since you can make a requreiments.txt file that will install PySimpleGUI or provide instructions in your readme.

The only licensing requirement for using an LGPL3 licensed piece of open source software is around posting a notification.  The LGPL and most of the others include the statement:
> Give prominent notice with each copy of the Combined Work that the Library is used in it and that the Library and its use are covered by this License.

Thank you for caring enough to ask!  

![image](https://user-images.githubusercontent.com/46163555/161391942-b7175779-1f5e-475c-9062-31ae0df2f31e.png)

You're a rare individual.

**Comment by adyrosebrigg** [comment]
Thank you for the input! I tried googling this but couldn’t find an answer, so: what would be the most appropriate place to include this notice? An about screen in the app’s UI? The readme? Somewhere else?

**Comment by PySimpleGUI** [comment]
The readme is perfect 

![image](https://user-images.githubusercontent.com/46163555/162343906-ed683ac9-5dd6-4e05-8ea4-c06105680204.png)
